[package]
authors = ["Sebastian Messmer <messmer@cryfs.org>"]
edition = "2021"
name = "git2version"
version = "0.1.0"
description = "This crate provides a way to get the version of the package from git."
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/git2version"
# TODO other config values, metadata, keywords, etc.

[dependencies]
konst = "^0.3.5"
git2 = {version = "^0.17.1", optional = true}
# TODO Ideally, serde should also be an optional dependency. We only need it for our integration tests.
serde = {version = "^1.0.163", features = ["derive"]}

[dev-dependencies]
tempdir = "^0.3.7"
rand = "^0.8.5"
serde_json = "^1.0.96"
git2 = "^0.17.1"

[features]
default = []

# The `build` feature enables the dependencies that are needed in the `build.rs` script of the proxy crate but not anymore at runtime
build = ["dep:git2"]
